# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import signaling_pb2 as signaling__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in signaling_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SignalingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOffer = channel.unary_unary(
                '/signaling.Signaling/SendOffer',
                request_serializer=signaling__pb2.OfferMessage.SerializeToString,
                response_deserializer=signaling__pb2.AnswerMessage.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/signaling.Signaling/SendMessage',
                request_serializer=signaling__pb2.ChatMessage.SerializeToString,
                response_deserializer=signaling__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.StreamMessages = channel.unary_stream(
                '/signaling.Signaling/StreamMessages',
                request_serializer=signaling__pb2.ChatMessage.SerializeToString,
                response_deserializer=signaling__pb2.ChatMessage.FromString,
                _registered_method=True)


class SignalingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOffer,
                    request_deserializer=signaling__pb2.OfferMessage.FromString,
                    response_serializer=signaling__pb2.AnswerMessage.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=signaling__pb2.ChatMessage.FromString,
                    response_serializer=signaling__pb2.ChatResponse.SerializeToString,
            ),
            'StreamMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=signaling__pb2.ChatMessage.FromString,
                    response_serializer=signaling__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'signaling.Signaling', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('signaling.Signaling', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Signaling(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/signaling.Signaling/SendOffer',
            signaling__pb2.OfferMessage.SerializeToString,
            signaling__pb2.AnswerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/signaling.Signaling/SendMessage',
            signaling__pb2.ChatMessage.SerializeToString,
            signaling__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/signaling.Signaling/StreamMessages',
            signaling__pb2.ChatMessage.SerializeToString,
            signaling__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
