# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signaling.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'signaling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsignaling.proto\x12\tsignaling\")\n\x0cOfferMessage\x12\x0b\n\x03sdp\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"*\n\rAnswerMessage\x12\x0b\n\x03sdp\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\":\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05\x64\x65\x62ug\x18\x42 \x01(\t\"-\n\x0c\x43hatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x65\x63ho\x18\x02 \x01(\t2\xcf\x01\n\tSignaling\x12>\n\tSendOffer\x12\x17.signaling.OfferMessage\x1a\x18.signaling.AnswerMessage\x12>\n\x0bSendMessage\x12\x16.signaling.ChatMessage\x1a\x17.signaling.ChatResponse\x12\x42\n\x0eStreamMessages\x12\x16.signaling.ChatMessage\x1a\x16.signaling.ChatMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signaling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OFFERMESSAGE']._serialized_start=30
  _globals['_OFFERMESSAGE']._serialized_end=71
  _globals['_ANSWERMESSAGE']._serialized_start=73
  _globals['_ANSWERMESSAGE']._serialized_end=115
  _globals['_CHATMESSAGE']._serialized_start=117
  _globals['_CHATMESSAGE']._serialized_end=175
  _globals['_CHATRESPONSE']._serialized_start=177
  _globals['_CHATRESPONSE']._serialized_end=222
  _globals['_SIGNALING']._serialized_start=225
  _globals['_SIGNALING']._serialized_end=432
# @@protoc_insertion_point(module_scope)
